trigger: none

pool:
  vmImage: windows-latest

steps:
- script: echo %FOO%
  displayName: 'Test the var'

- task: DotNetCoreCLI@2
  displayName: Run the test
  inputs:
    command: 'test'
    projects: 'EnvironmentVariableTest/EnvironmentVariableTest.csproj'
