name: Deploy Meekly
on:
  push:
    branches:
      - main
    paths:
      - 'Meekly/**'
      - '.github/workflows/meekly.yml'

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-meekly
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Publish container
        run: dotnet publish ./Meekly/Meekly.Web/Meekly.Web.csproj --os linux --arch x64 /t:PublishContainer
