name: Ride-CD

on:
  push:
    branches:
    - main
    paths:
    - 'RideScheduler/**'
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'RideScheduler/RideScheduler/appsettings.json'
        env:
          ConnectionStrings.CosmosUri: https://ridescheduler.documents.azure.com:443/
          ConnectionStrings.CosmosKey: ${{ secrets.cosmos_key }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: RideScheduler/RideScheduler
          push: true
          tags: jamers99/ridescheduler:latest
